model_type: panopticon
image_resolution: 224
embed_dim: 768
patch_size: 14

run_dir: /hkfs/work/workspace/scratch/tum_mhj8661-panopticon/dino_logs/abl/p2/ibot/ibot=2.0/lr=5e-4_e=30b-1_warmup=5

segm_blk_indices: [3, 5, 7, 11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]
default_feat_out_dim: 768