model_type: panopticon
image_resolution: 224
embed_dim: 768
patch_size: 14
run_dir: /data/panopticon/logs/dino_logs/horeka/chnsim/lr=5e-4_warmup=5_hold_epochs=0_min_lr=1e-6_frz=last_layer=1_break_at_epochs=-1_bsz=75
segm_blk_indices: [3, 5, 7, 11]
accel_cls_blk_indices: [8, 9, 10, 11]
default_cls_blk_indices: [11]
default_feat_out_dim: 768
replace_pe: false
full_spectra: true